<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="pool_table">
  
  <!-- Define Parameters -->
  <xacro:property name="table_leg_radius" value="0.075"/>
  <xacro:property name="table_leg_length" value="0.5"/>
  
  <xacro:property name="table_inner_width" value="0.82"/>
  <xacro:property name="table_outer_width" value="1.12"/>
  <xacro:property name="table_inner_length" value="1.6"/>
  <xacro:property name="table_outer_length" value="1.9"/>
  <xacro:property name="table_inner_height" value="0.75"/>
  <xacro:property name="table_outer_height" value="0.8"/>

  <xacro:property name="tabletop_inner_height" value="${table_inner_height-table_leg_length}"/>
  <xacro:property name="tabletop_outer_height" value="${table_outer_height-table_leg_length}"/>
  
  <!-- Define macro for table legs -->
  <xacro:macro name="table_leg" params="name">
    <link name="table_leg_${name}">
      <visual>
        <geometry>
          <cylinder radius="${table_leg_radius}" length="${table_leg_length}"/>
        </geometry>
        <origin xyz="0 0 -${table_leg_length/2}"/>
        <material name="brown"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${table_leg_radius}" length="${table_leg_length}"/>
        </geometry>
        <origin xyz="0 0 -${table_leg_length/2}"/>
      </collision> 
    </link>
  </xacro:macro>
  
    
  <!-- Define Materials -->
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <material name="brown">
    <color rgba="0.56 0.32 0.12 1"/>
  </material>

  <material name="green">
    <color rgba="0 0.5 0 1"/>
  </material>

  <!-- Define links and joints -->

  <link name="world">
  </link>

  <link name="tabletop">
    <visual>
      <geometry>
        <box size="${table_outer_width} ${table_outer_length} ${tabletop_inner_height}"/>
      </geometry>
      <origin xyz="0 0 ${(tabletop_inner_height)/2}"/>
      <material name="green"/>
    </visual>
    <collision>
      <geometry>
        <box size="${table_outer_width} ${table_outer_length} ${tabletop_inner_height}"/>
      </geometry>
      <origin xyz="0 0 ${(tabletop_inner_height)/2}"/>
    </collision>
  </link>
  <joint name="tabletop_to_world" type="fixed">
    <parent link="world"/>
    <child link="tabletop"/>
    <origin xyz="0 0 ${table_leg_length}"/>
  </joint>

  <!-- table_frame_ends, table_frame_sides -->

  <xacro:table_leg name="FL"/>
  <xacro:table_leg name="BL"/>
  <xacro:table_leg name="FR"/>
  <xacro:table_leg name="BR"/>

  <joint name="table_leg_FL_to_tabletop" type="fixed">
    <parent link="tabletop"/>
    <child link="table_leg_FL"/>
    <origin xyz="${table_inner_width/2} ${table_inner_length/2} 0"/>
  </joint>
  <joint name="table_leg_BL_to_tabletop" type="fixed">
    <parent link="tabletop"/>
    <child link="table_leg_BL"/>
    <origin xyz="${-table_inner_width/2} ${table_inner_length/2} 0"/>
  </joint>
  <joint name="table_leg_FR_to_tabletop" type="fixed">
    <parent link="tabletop"/>
    <child link="table_leg_FR"/>
    <origin xyz="${table_inner_width/2} ${-table_inner_length/2} 0"/>
  </joint>
  <joint name="table_leg_BR_to_tabletop" type="fixed">
    <parent link="tabletop"/>
    <child link="table_leg_BR"/>
    <origin xyz="${-table_inner_width/2} ${-table_inner_length/2} 0"/>
  </joint>



</robot>
